function(add_object_file TARGET)
    if(NOT EXISTS "${TARGET}.o")
        if(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
            execute_process(COMMAND gcc -c "${TARGET}.c")
        else()
            message(STATUS "add_object_file only work with GNU")
            return()
        endif()
    else()
        message(STATUS "${TARGET}.o exists" )
    endif()
endfunction(add_object_file)

function(object_dump TARGET)
    if(NOT EXISTS "${TARGET}.o")
        add_object_file(${TARGET})
    endif()

    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        execute_process(COMMAND objdump -x "${TARGET}.o")
    else()
        message(STATUS "object_dump only work with GNU")
        return()
    endif()
endfunction(object_dump)

function(target_memory_size TARGET)
    if(NOT EXISTS "${CMAKE_SOURCE_DIR}/build/${TARGET}")
        message(STATUS "${TARGET} doesn't exists")
        return()
    endif()

    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        execute_process(COMMAND size "${CMAKE_SOURCE_DIR}/build/${TARGET}")
    else()
        message(STATUS "target_memory_size work with GNU")
        return()
    endif()
endfunction(target_memory_size)